# Generated by Django 4.2.1 on 2023-05-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0003_remove_studenttest_passtest_studenttest_passtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttest',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
