# Generated by Django 4.2.1 on 2023-05-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0004_studenttest_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttest',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
