# Generated by Django 4.2.1 on 2023-05-14 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0005_studenttest_success'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studenttest',
            old_name='success',
            new_name='succses',
        ),
    ]
